-- Phase 6: in-app notifications, generated by triggers on likes/comments/messages/group invites.
-- Run this in the Supabase SQL Editor. Safe to re-run.

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('like', 'comment', 'message', 'group_invite')),
  post_id uuid references public.posts(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete cascade,
  group_id uuid references public.groups(id) on delete cascade,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;

drop policy if exists "users can see their own notifications" on public.notifications;
create policy "users can see their own notifications"
  on public.notifications for select
  to authenticated
  using (user_id = auth.uid());

-- No insert policy: notifications are only ever created by the security-definer
-- trigger functions below, never directly by a client.

drop policy if exists "users can mark their own notifications read" on public.notifications;
create policy "users can mark their own notifications read"
  on public.notifications for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create or replace function public.notify_on_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  post_author uuid;
begin
  select author_id into post_author from public.posts where id = new.post_id;
  if post_author is not null and post_author <> new.user_id then
    insert into public.notifications (user_id, actor_id, type, post_id)
    values (post_author, new.user_id, 'like', new.post_id);
  end if;
  return new;
end;
$$;

drop trigger if exists on_post_like_created on public.post_likes;
create trigger on_post_like_created
  after insert on public.post_likes
  for each row execute function public.notify_on_like();

create or replace function public.notify_on_comment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  post_author uuid;
begin
  select author_id into post_author from public.posts where id = new.post_id;
  if post_author is not null and post_author <> new.author_id then
    insert into public.notifications (user_id, actor_id, type, post_id, comment_id)
    values (post_author, new.author_id, 'comment', new.post_id, new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists on_comment_created on public.comments;
create trigger on_comment_created
  after insert on public.comments
  for each row execute function public.notify_on_comment();

create or replace function public.notify_on_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, actor_id, type, conversation_id)
  select cp.user_id, new.sender_id, 'message', new.conversation_id
  from public.conversation_participants cp
  where cp.conversation_id = new.conversation_id and cp.user_id <> new.sender_id;
  return new;
end;
$$;

drop trigger if exists on_message_created on public.messages;
create trigger on_message_created
  after insert on public.messages
  for each row execute function public.notify_on_message();

create or replace function public.notify_on_group_invite()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  grp_creator uuid;
begin
  select created_by into grp_creator from public.groups where id = new.group_id;
  if grp_creator is not null and grp_creator <> new.user_id then
    insert into public.notifications (user_id, actor_id, type, group_id)
    values (new.user_id, grp_creator, 'group_invite', new.group_id);
  end if;
  return new;
end;
$$;

drop trigger if exists on_group_member_added on public.group_members;
create trigger on_group_member_added
  after insert on public.group_members
  for each row execute function public.notify_on_group_invite();

drop view if exists public.notification_feed;
create view public.notification_feed
  with (security_invoker = true)
  as
  select
    n.id,
    n.type,
    n.read,
    n.created_at,
    n.post_id,
    n.comment_id,
    n.conversation_id,
    n.group_id,
    a.username as actor_username,
    a.display_name as actor_display_name,
    a.avatar_url as actor_avatar_url
  from public.notifications n
  join public.profiles a on a.id = n.actor_id
  where n.user_id = auth.uid()
  order by n.created_at desc;

grant select on public.notification_feed to authenticated;

-- Enable realtime delivery for new notifications (idempotent).
do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then
  null;
end $$;
