import type { PostFeedItem, Profile } from '../types';

// Fake, view-only preview data - never touches Supabase. Ids are prefixed
// "demo-" so PostCard/UserProfileScreen/FriendsGrid can recognize them and
// keep interactions purely local (no network calls against fake ids).
export const DEMO_PROFILES: Profile[] = [
  {
    id: 'demo-1',
    username: 'ana.beatriz',
    display_name: 'Ana Beatriz',
    avatar_url: null,
    bio: 'Vivendo um dia de cada vez. Café antes de tudo.',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-2',
    username: 'joao.pedro',
    display_name: 'João Pedro',
    avatar_url: null,
    bio: 'Futebol de várzea aos domingos.',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-3',
    username: 'carla.mendes',
    display_name: 'Carla Mendes',
    avatar_url: null,
    bio: 'Fotografia amadora, viagens baratas.',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-4',
    username: 'lucas.tavares',
    display_name: 'Lucas Tavares',
    avatar_url: null,
    bio: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'demo-5',
    username: 'marina.rocha',
    display_name: 'Marina Rocha',
    avatar_url: null,
    bio: 'Sempre planejando a próxima viagem.',
    created_at: '2026-01-01T00:00:00Z',
  },
];

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

export const DEMO_POSTS: PostFeedItem[] = [
  {
    id: 'demo-post-1',
    author_id: 'demo-1',
    content: 'Domingo de sol e preguiça. Recomendo. ☀️',
    media_urls: [],
    visibility: 'friends',
    group_id: null,
    created_at: hoursAgo(2),
    group_name: null,
    author_username: 'ana.beatriz',
    author_display_name: 'Ana Beatriz',
    author_avatar_url: null,
    like_count: 4,
    comment_count: 1,
    liked_by_me: false,
  },
  {
    id: 'demo-post-2',
    author_id: 'demo-2',
    content: 'Perdemos de 5 a 4 no pênalti mas o churrasco depois compensou tudo kkkk',
    media_urls: [],
    visibility: 'friends',
    group_id: null,
    created_at: hoursAgo(5),
    group_name: null,
    author_username: 'joao.pedro',
    author_display_name: 'João Pedro',
    author_avatar_url: null,
    like_count: 7,
    comment_count: 3,
    liked_by_me: true,
  },
  {
    id: 'demo-post-3',
    author_id: 'demo-3',
    content: 'Testando a câmera nova no pôr do sol de hoje. Ainda aprendendo os ajustes manuais.',
    media_urls: [],
    visibility: 'everyone',
    group_id: null,
    created_at: hoursAgo(9),
    group_name: null,
    author_username: 'carla.mendes',
    author_display_name: 'Carla Mendes',
    author_avatar_url: null,
    like_count: 12,
    comment_count: 2,
    liked_by_me: false,
  },
  {
    id: 'demo-post-4',
    author_id: 'demo-5',
    content: 'Passagem pra Fortaleza saiu baratíssima, quem topa em outubro?',
    media_urls: [],
    visibility: 'friends',
    group_id: null,
    created_at: hoursAgo(14),
    group_name: null,
    author_username: 'marina.rocha',
    author_display_name: 'Marina Rocha',
    author_avatar_url: null,
    like_count: 3,
    comment_count: 5,
    liked_by_me: false,
  },
  {
    id: 'demo-post-5',
    author_id: 'demo-4',
    content: 'Alguém mais só quer dormir até quarta-feira?',
    media_urls: [],
    visibility: 'friends',
    group_id: null,
    created_at: hoursAgo(20),
    group_name: null,
    author_username: 'lucas.tavares',
    author_display_name: 'Lucas Tavares',
    author_avatar_url: null,
    like_count: 9,
    comment_count: 0,
    liked_by_me: false,
  },
  {
    id: 'demo-post-6',
    author_id: 'demo-1',
    content: 'Fiz pão de fermentação natural pela primeira vez e não cresceu quase nada. Amanhã tento de novo.',
    media_urls: [],
    visibility: 'friends',
    group_id: null,
    created_at: hoursAgo(30),
    group_name: null,
    author_username: 'ana.beatriz',
    author_display_name: 'Ana Beatriz',
    author_avatar_url: null,
    like_count: 6,
    comment_count: 2,
    liked_by_me: true,
  },
];
